on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  build-ci-image:
    runs-on: curator-server
    steps:
      - uses: actions/checkout@v6

      - name: Build the 'curator-server' image
        run: |
          docker build -t curator-server --target serverprod .

      - name: Build the 'curator-server-nginx-prod' image
        run: |
          docker build -t curator-server-nginx-prod --target nginxprod .
      
      - name: Re-write .env file
        run: |
          [ -f .env ] && rm .env
          echo "NODE_ENV=production" >> .env
          echo "SERVER_URL=https://latest.curator.bellbellbell.com" >> .env
          echo "SERVER_PORT=443" >> .env
          echo "DATABASE_URL=postgres://user:pass@db/app" >> .env
          echo "BETTER_AUTH_SECRET=${{ secrets.CURATOR_SERVER_LATEST_BETTER_AUTH_SECRET }}" >> .env
      # - name: Stop the 'prod' profile
      #   run: |
      #     docker compose --profile prod down

      - name: Start the 'prod' profile, w/--force-recreate
        run: |
          docker compose --profile prod up --force-recreate --always-recreate-deps -d