/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as OverviewImport } from './routes/overview'
import { Route as IndexImport } from './routes/index'
import { Route as SettingsStatusImport } from './routes/settings.status'

// Create/Update Routes

const OverviewRoute = OverviewImport.update({
  id: '/overview',
  path: '/overview',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const SettingsStatusRoute = SettingsStatusImport.update({
  id: '/settings/status',
  path: '/settings/status',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/overview': {
      id: '/overview'
      path: '/overview'
      fullPath: '/overview'
      preLoaderRoute: typeof OverviewImport
      parentRoute: typeof rootRoute
    }
    '/settings/status': {
      id: '/settings/status'
      path: '/settings/status'
      fullPath: '/settings/status'
      preLoaderRoute: typeof SettingsStatusImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/settings/status': typeof SettingsStatusRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/settings/status': typeof SettingsStatusRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/overview': typeof OverviewRoute
  '/settings/status': typeof SettingsStatusRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/overview' | '/settings/status'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/overview' | '/settings/status'
  id: '__root__' | '/' | '/overview' | '/settings/status'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  OverviewRoute: typeof OverviewRoute
  SettingsStatusRoute: typeof SettingsStatusRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  OverviewRoute: OverviewRoute,
  SettingsStatusRoute: SettingsStatusRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/overview",
        "/settings/status"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/overview": {
      "filePath": "overview.tsx"
    },
    "/settings/status": {
      "filePath": "settings.status.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
