/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as PoliciesRouteImport } from './routes/policies'
import { Route as OrgConfigurationRouteImport } from './routes/org-configuration'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ExhibitsRouteImport } from './routes/exhibits'
import { Route as AutomationsRouteImport } from './routes/automations'
import { Route as IndexRouteImport } from './routes/index'

const PoliciesRoute = PoliciesRouteImport.update({
  id: '/policies',
  path: '/policies',
  getParentRoute: () => rootRouteImport,
} as any)
const OrgConfigurationRoute = OrgConfigurationRouteImport.update({
  id: '/org-configuration',
  path: '/org-configuration',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ExhibitsRoute = ExhibitsRouteImport.update({
  id: '/exhibits',
  path: '/exhibits',
  getParentRoute: () => rootRouteImport,
} as any)
const AutomationsRoute = AutomationsRouteImport.update({
  id: '/automations',
  path: '/automations',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/exhibits': typeof ExhibitsRoute
  '/login': typeof LoginRoute
  '/org-configuration': typeof OrgConfigurationRoute
  '/policies': typeof PoliciesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/exhibits': typeof ExhibitsRoute
  '/login': typeof LoginRoute
  '/org-configuration': typeof OrgConfigurationRoute
  '/policies': typeof PoliciesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/automations': typeof AutomationsRoute
  '/exhibits': typeof ExhibitsRoute
  '/login': typeof LoginRoute
  '/org-configuration': typeof OrgConfigurationRoute
  '/policies': typeof PoliciesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/automations'
    | '/exhibits'
    | '/login'
    | '/org-configuration'
    | '/policies'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/automations'
    | '/exhibits'
    | '/login'
    | '/org-configuration'
    | '/policies'
  id:
    | '__root__'
    | '/'
    | '/automations'
    | '/exhibits'
    | '/login'
    | '/org-configuration'
    | '/policies'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AutomationsRoute: typeof AutomationsRoute
  ExhibitsRoute: typeof ExhibitsRoute
  LoginRoute: typeof LoginRoute
  OrgConfigurationRoute: typeof OrgConfigurationRoute
  PoliciesRoute: typeof PoliciesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/automations': {
      id: '/automations'
      path: '/automations'
      fullPath: '/automations'
      preLoaderRoute: typeof AutomationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exhibits': {
      id: '/exhibits'
      path: '/exhibits'
      fullPath: '/exhibits'
      preLoaderRoute: typeof ExhibitsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/org-configuration': {
      id: '/org-configuration'
      path: '/org-configuration'
      fullPath: '/org-configuration'
      preLoaderRoute: typeof OrgConfigurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/policies': {
      id: '/policies'
      path: '/policies'
      fullPath: '/policies'
      preLoaderRoute: typeof PoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AutomationsRoute: AutomationsRoute,
  ExhibitsRoute: ExhibitsRoute,
  LoginRoute: LoginRoute,
  OrgConfigurationRoute: OrgConfigurationRoute,
  PoliciesRoute: PoliciesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
